application:
  port: 8000
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  # Only setting the development value, we'll deal with the
  # production token outside of version control
  # since it is a sensitive secret
  authorization_token: "my-secret-token"