application:
  host: 0.0.0.0
  base_url: "https://zero2prod-mnodh.ondigitalocean.app"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "taha@tahaafzal.com"