name: Rust

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Run tests
          uses: actions-rs/cargo@v1
          with:
            command: test

    linting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Run clippy
          run: cargo clippy -- -D warnings --all-features
    
    formatting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true
        
        - name: Install rustfmt
          run: rustup component add rustfmt
        
        - name: Run rustfmt
          uses: actions-rs/cargo@v1
          with:
            command: fmt
            args: --all -- --check
    
    coverage:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Install toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Install tarpaulin
          run: cargo install cargo-tarpaulin

        - name: Generate code coverage
          run: cargo tarpaulin --verbose --workspace --ignore-tests
